### ISSUE TITLE
inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by proxgrewal** [aquibjaved/Real-time-face-recognition-in-python-using-opencv-#1]
Proxs-Air:Real-time prox$ python3 real_time.py 
  File "real_time.py", line 25
    images.append(cv2.imread(path,0))
                                    ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by hunaidkhan2000** [comment]
Use this 
for (subdirs, dirs, files) in os.walk(fn_dir):
    for subdir in dirs:
        names[id] = subdir
        subjectpath = os.path.join(fn_dir, subdir)
        for filename in os.listdir(subjectpath):
            path = subjectpath + '/' + filename
            lable = id
	    images.append(cv2.imread(path, 0))
            lables.append(int(lable)) 
        id += 1

**Comment by aquibjaved** [comment]
@proxAdmin  It might be possible that you are using python 3, In python 3 you can use either of anyone TAB or SPACES but not both. 
Please check and let us know.
