### ISSUE TITLE
Numbers near a persons name what it shows?

### ISSUE THREAD

**Issue by hunaidkhan2000** [aquibjaved/Real-time-face-recognition-in-python-using-opencv-#2]
when i run the script face_recognize  it shows the persons name and it also shows some numbers between 100 to 500 . can anyone tell me what it signifies? probability

**Comment by aquibjaved** [comment]
@hunaidkhan2000  It's the confidence of the classifier, It is the distance between your query image and the closest in the train set.
It's smaller the better, so don't get confused. 
You can tweak the value of it and much more accurate.
