### ISSUE TITLE
Plz help buddy ....

### ISSUE THREAD

**Issue by Gauravgautam2004** [aquibjaved/Real-time-face-recognition-in-python-using-opencv-#3]
I am getting this error while running Create_database_test.py

fn_name = sys.argv[1]  # name of the person
IndexError: list index out of range

**Comment by aquibjaved** [comment]
Hi @Gauravgautam2004  How are you running the code? 

`python create_database.py person_name`

**Comment by Gauravgautam2004** [comment]
Thanks for the reply brother ....i got it fixed .... was running it the wrong way ....

**Comment by Gauravgautam2004** [comment]
Thanks for the reply brother ....i got it fixed .... was running it the
wrong way ....

Maj Gaurav Kumar Gautam
Indian Army
09685004900

**Comment by aquibjaved** [comment]
Glad you fixed it Bro,
Thank you
