### ISSUE TITLE
Confusion related to python Scripts!

### ISSUE THREAD

**Issue by Aashima-Gupta** [aquibjaved/Real-time-face-recognition-in-python-using-opencv-#5]
Hi,
I downloaded your code from github. Now their are various python scripts Like
create_data.py
face_recognize.py
create_database.py
real_time.py
trainer.py

It seems to be confusing to know which file is doing what.
Please brief me bout them asap.

**Comment by aquibjaved** [comment]
Hi @Aashima-Gupta,
Please use the recently committed codes, 

Run the code create_database.py with the parameter name.
$ python create_database.py you_name
Create atleast two dataset,
Then run the code, face_rec.py
$ python face_rec.py
